# Every time is taken in seconds!

language: "en" # Supported languages -> hu, de, en
time: 216000 # Starting time
damage-per-half-heart: 120 # Time taken by half heart.
add-time-per-half-heart: 60 # Time given by half heart
egapple-time: 1800 # Time given by an eaten enchanted golden apple
gapple-time: 900 # Time given by an eaten NORMAL golden apple

countdown:
  time: 3 # Time to countdown before starting the match.
  title: "&aThe match is about to start in..."
  subtitle: "&2{time} &aseconds!"

end:
  title: "&c&lGAME OVER"
  subtitle: "&e&lTHE WINNER IS &6{winner}"
  broadcast: "&6{winner} &ahas won the match! &2GG!"

potions:
  healing: 1800 # Time given by a used healing potion
  regeneration: 900 # Time given by a used regeneration potion

minimum-players: 2 # The amount of players it should find when the match starts

action-bar: "{color}{time}" # Information to show on the Actionbar

color-per-life:
  dark-green: "216000-180000" # 60H-50H
  lime: "180000-144000" # 50H-40H
  yellow: "144000-108000" # 40H-30H
  orange: "108000-72000" # 30H-20H
  red: "72000-36000" # 20H-10H
  violet: "36000-0" # 10H-0

color-name:
  dark-green: "&2&lDARK GREEN"
  lime: "&a&lLIME"
  yellow: "&e&lYELLOW"
  orange: "&6&lORANGE"
  red: "&c&lRED"
  violet: "&d&lVIOLET"

database:
  type: "sqlite" # Supported types -> mysql, sqlite
  mysql:
    host: localhost
    port: 3306
    database: coma112
    username: root
    password: ""
    # You shouldn't touch this part except if you are familiar with it.
    ssl: false
    certificateverification: false
    poolsize: 10
    lifetime: 1800000

# Webhook
# webhook.enabled -> You can enable and disable the webhook feature
# webhook.url -> Discord Webhook URL

webhook:
  match-start-embed:
    enabled: false
    url: "WEBHOOK URL HERE!!!"
    title: "NEW MATCH!"
    description: "Players in the match: {count}"
    color: "GREEN"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CLIFE"
    footer-icon: ""
    thumbnail: ""
    image: ""
  match-end-embed:
    enabled: false
    url: "WEBHOOK URL HERE!!!"
    title: "MATCH ENDED!"
    description: "Winner: {winner}"
    color: "GREEN"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CLIFE"
    footer-icon: ""
    thumbnail: ""
    image: ""
  match-kill-embed:
    enabled: false
    url: "WEBHOOK URL HERE!!!"
    title: "NEW KILL"
    description: "**{killer}** killed **{victim}**"
    color: "GREEN"
    author-name: ""
    author-url: ""
    author-icon: ""
    footer-text: "SENT BY CLIFE"
    footer-icon: ""
    thumbnail: ""
    image: ""

rtp-enabled: true # RandomTP when the match starts.
chest-enabled: true # Starting chests when the match starts
chest-in-area: 5 # Number of chests spawned in the center and radius.
loot-in-one-chest: 2 # Number of loot in one chest. I recommend that this number should be lower than the amount of loots below.

chest-loot:
  1:
    amount: 1
    material: "ENCHANTED_GOLDEN_APPLE"
    name: "&a&lFREE LIFE!!444!!"
    lore:
      - ""
      - "&2Gives you some minute."
    chance: "5"
  2:
    amount: 1
    material: "GOLDEN_APPLE"
    name: "&a&lFREE LIFE (POOR)"
    lore:
      - ""
      - "&2Gives you some minute."
    chance: "10"
  3:
    amount: 2
    material: "DIAMOND"
    name: "&bHelp at the start;)"
    lore:
      - ""
      - "&aCraft something :)"
    chance: "20"
  4:
    amount: 1
    material: "STICK"
    name: "&fNothing..."
    lore:
      - ""
      - "&fI mean, it's really nothing.."
    chance: "70"